################################################################################
# Copyright (c) IBM Corporation 2020
#
# Description:
#    This playbook will generate documentation for all collections in the
#    registry.yml, perform validation, allow for a preview of generated doc
#    and upload to gh-pages.
#
# Group_vars:
#    Booleans designed to control the flow of this playbook to run this
#    playbook headless. See group_vars/all.yml for more information.
#
#    deploy_to_gh_pages - default is True, it will instruct the playbook to
#       deploy the generated HTML to the doc-site (site/gh-pages).
#
# Usage:
#    ansible-playbook -i inventory site-builder.yml
################################################################################

---
- hosts: all
  gather_facts: no
  connection: local

  # ##############################################################################
  # # Parse 'registry.yml' for certified contributors (key:value)
  # ##############################################################################

  tasks:
    - name: Copy the generated HTML from `build/html/` to `site/gh-pages/`
      shell: |
          cd site/gh-pages
          git checkout gh-pages
          cp -R ../../build/html/* .
          git add .
          git status
          git commit -m "Automated commit to update documentation"
          git push -f
          cd ../..
          git checkout master
          git status
          git submodule update
      register: git_update_doc

    - name: Display the HTML content uploaded to the doc site (gh-pages)
      debug: msg="{{ git_update_doc }}"

################################################################################
# If the content has been built and pushed to gh-pages, display the URL to the 
# user
################################################################################
    # See https://ibm.github.io/z_ansible_collections_doc/index.html
    - name: Follow this URL to view the updated collection content
      debug: msg="https://ibm.github.io/z_ansible_collections_doc/index.html"
      when: deploy_to_gh_pages